remote_theme: "mmistakes/so-simple-theme@3.2.0"  # Yoki "willianjusten/cards-jekyll-template" uchun moslashtiring
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
paginate: 10  # Har sahifada 10 ta post
paginate_path: "/page:num/"
title: "Tukhliev's CTF Writeups"
description: "CTF va vulnerability writeuplari"
url: "https://tukhliev.github.io"
baseurl: ""
author:
  name: "Your Name"
  twitter: "your_twitter"
  picture: /assets/img/author.jpg  # Profil rasm
skin: "/assets/css/skins/dark.css"  # Dark mode uchun
search_full_content: true  # To'liq postlarni qidirish uchun (So Simple uchun)
